/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'TheGrid' at '10/8/16 4:13 PM' with Gradle 2.13
 *
 * @author TheGrid, @date 10/8/16 4:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
